#!/usr/bin/env bash
# Configures localhost and facebook.com name resolution

cp /etc/hosts /etc/hosts.bak
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost$/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
