#!/usr/bin/env bash
# Changes localhost and facebook.com resolution in /etc/hosts

tmp_file="/tmp/hosts.tmp"

grep -vE '^[[:space:]]*127\.0\.0\.1[[:space:]]+localhost$|[[:space:]]facebook\.com$|[[:space:]]localhost$' /etc/hosts > "$tmp_file"

{
  echo "127.0.0.2 localhost"
  echo "8.8.8.8 facebook.com"
  cat "$tmp_file"
} > /etc/hosts

rm -f "$tmp_file"
